# -*- coding: utf-8 -*-
"""arbol1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcxZ_EYBAJGEcy3Nk1P1P36mNKoyn3Fv
"""

#ANDRES FELIPE PORRAS GARZON
#JEISSON DAVID INFANTE LEAL

#DATASET

animales = [
{
    "nom_animal": "mangosta",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "selva",
    "tamano_animal": "pequeno",
    "color_caracteristico": "",
    "reproduccion": "viviparo",
    "actitud": "agresiva"
  },
{
    "nom_animal": "polilla",
    "clase": "insecto",
    "dieta": "nectarivoros",
    "extremidades": 6,
    "Tipo_de_pelaje": "bellos",
    "sensacion_de_pelaje": "suave",
    "hogar": "sabana",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "inofensivo"
  },
{
    "nom_animal": "triton",
    "clase": "anfibio",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "agua",
    "tamano_animal": "pequeno",
    "color_caracteristico": "marron",
    "reproduccion": "ovipara",
    "actitud": "inofensivo"
  },
{
    "nom_animal": "pulpo",
    "clase": "molusco",
    "dieta": "carnivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "pequeño",
    "color_caracteristico": "morado",
    "reproduccion": "ovipara",
    "actitud": "escurridizo"
  },
{
    "nom_animal": "zarigüeya",
    "clase": "marsupial",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "pelo",
    "sensacion_de_pelaje": "aspero",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "vivipara",
    "actitud": "agresivo"
  },
{
    "nom_animal": "gazella",
    "clase": "antilope",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "pelo",
    "sensacion_de_pelaje": "suave",
    "hogar": "africa",
    "tamano_animal": "mediano",
    "color_caracteristico": "marron",
    "reproduccion": "vivipara",
    "actitud": "nervioso"
  },
{
    "nom_animal": "avestruz",
    "clase": "ave",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suaves",
    "hogar": "africa",
    "tamano_animal": "grande",
    "color_caracteristico": "gris",
    "reproduccion": "ovipara",
    "actitud": "agresivo"
  },
{
    "nom_animal": "perico",
    "clase": "ave",
    "dieta": "frutiboro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "selva",
    "tamano_animal": "pequeño",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "calmado"
  },
{
    "nom_animal": "pinguino",
    "clase": "ave",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "antartida",
    "tamano_animal": "mediano",
    "color_caracteristico": "negro",
    "reproduccion": "oviparo",
    "actitud": "calmada"
  },
{
    "nom_animal": "faisán",
    "clase": "galliforme",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "sauve",
    "hogar": "asia",
    "tamano_animal": "pequeño",
    "color_caracteristico": "cafe",
    "reproduccion": "ovipara",
    "actitud": "nerviosa"
  },
{
    "nom_animal": "lucio",
    "clase": "pez",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "suave",
    "hogar": "rios",
    "tamano_animal": "mediano",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "pirana",
    "clase": "pez",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "suave",
    "hogar": "amazonas",
    "tamano_animal": "pequeno",
    "color_caracteristico": "plateado",
    "reproduccion": "ovipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "Vibora",
    "clase": "viperidos",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "ornitorrinco",
    "clase": "mamifero",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "pelo",
    "sensacion_de_pelaje": "suave",
    "hogar": "australia",
    "tamano_animal": "pequeño",
    "color_caracteristico": "marron",
    "reproduccion": "oviparo",
    "actitud": "calmado"
  },
{
    "nom_animal": "huron",
    "clase": "mustelido",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "pelo",
    "sensacion_de_pelaje": "suave",
    "hogar": "variado",
    "tamano_animal": "pequeño",
    "color_caracteristico": "gris",
    "reproduccion": "vivipara",
    "actitud": "inquieto"
  },
{
    "nom_animal": "poni",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "granjas",
    "tamano_animal": "mediano",
    "color_caracteristico": "multicolor",
    "reproduccion": "vivipara",
    "actitud": "inofensivo"
  },
{
    "nom_animal": "marsopa",
    "clase": "cetaceo",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "jugueton"
  },
{
    "nom_animal": "puma",
    "clase": "felino",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "montaña",
    "tamano_animal": "mediano",
    "color_caracteristico": "marron",
    "reproduccion": "vivipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "caracal",
    "clase": "falino",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "sabana",
    "tamano_animal": "pequeno",
    "color_caracteristico": "veige",
    "reproduccion": "viviparo",
    "actitud": "agresivo"
  },
{
    "nom_animal": "mapache",
    "clase": "mamifero",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "vivipara",
    "actitud": "curioso"
  },
{
    "nom_animal": "reno",
    "clase": "rumiante",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "grande",
    "color_caracteristico": "marron",
    "reproduccion": "vivipara",
    "actitud": "nervioso"
  },
{
    "nom_animal": "nandú",
    "clase": "ave",
    "dieta": "herbivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "suramerica",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "ovipara",
    "actitud": "nervioso"
  },
{
    "nom_animal": "escorpion",
    "clase": "arcanido",
    "dieta": "insectivoro",
    "extremidades": 9,
    "Tipo_de_pelaje": "exoesqueleto",
    "sensacion_de_pelaje": "aspero",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "marron",
    "reproduccion": "oviparo",
    "actitud": "agresivo"
  },
{
    "nom_animal": "foca",
    "clase": "pinnipedo",
    "dieta": "carnivoro",
    "extremidades": 3,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "sueve",
    "hogar": "antartida",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "calmado"
  },
{
    "nom_animal": "leonmarino",
    "clase": "pinnipedo",
    "dieta": "carnivoro",
    "extremidades": 3,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "marron",
    "reproduccion": "viviparo",
    "actitud": "agresivo"
  },
{
    "nom_animal": "serpiente marina",
    "clase": "reptil",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "agresivo"
  },
{
    "nom_animal": "avispa de mar",
    "clase": "chirodropida",
    "dieta": "carnivoro",
    "extremidades": 6,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "translucido",
    "reproduccion": "asexual",
    "actitud": "calmada"
  },
{
    "nom_animal": "gaviota",
    "clase": "ave",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "blanco",
    "reproduccion": "oviparo",
    "actitud": "calmado"
  },
{
    "nom_animal": "fregata",
    "clase": "sulidoforme",
    "dieta": "carnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "tropical",
    "tamano_animal": "grande",
    "color_caracteristico": "negro",
    "reproduccion": "ovipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "babosa",
    "clase": "molusto",
    "dieta": "hervivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "babosa",
    "hogar": "diverso",
    "tamano_animal": "pequeno",
    "color_caracteristico": "cafe",
    "reproduccion": "ovipara",
    "actitud": "inofensiva"
  },
{
    "nom_animal": "lenguado",
    "clase": "soleido",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "suave",
    "hogar": "tropico",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "nervioso"
  },
{
    "nom_animal": "gorrion",
    "clase": "paseriforme",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "urbano",
    "tamano_animal": "pequeno",
    "color_caracteristico": "cafe",
    "reproduccion": "oviparo",
    "actitud": "pacifico"
  },
{
    "nom_animal": "ardilla",
    "clase": "roedor",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "urbano",
    "tamano_animal": "pequeno",
    "color_caracteristico": "marron",
    "reproduccion": "vivipara",
    "actitud": "jugueton"
  },
{
    "nom_animal": "estrella de mar",
    "clase": "invertebrado",
    "dieta": "carnivoro",
    "extremidades": 5,
    "Tipo_de_pelaje": "calcificado",
    "sensacion_de_pelaje": "duro",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "asexual",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "mantaralla",
    "clase": "elasmobranquio",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "lisa",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "azul",
    "reproduccion": "ovipara",
    "actitud": "tranquila"
  },
{
    "nom_animal": "cisne",
    "clase": "anseriforme",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "lagos",
    "tamano_animal": "mediano",
    "color_caracteristico": "blanco",
    "reproduccion": "ovipara",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "termita",
    "clase": "neoptero",
    "dieta": "herbivioro",
    "extremidades": 6,
    "Tipo_de_pelaje": "exoesqueleto",
    "sensacion_de_pelaje": "duro",
    "hogar": "subterraneo",
    "tamano_animal": "pequeno",
    "color_caracteristico": "ambar",
    "reproduccion": "oviparo",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "salamandra",
    "clase": "anfibio",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "rugoso",
    "hogar": "rios",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multiple",
    "reproduccion": "oviparo",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "tortuga",
    "clase": "reptil",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "caparazon",
    "sensacion_de_pelaje": "duro",
    "hogar": "sabana",
    "tamano_animal": "mediano",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "tuatara",
    "clase": "resptil",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "aspero",
    "hogar": "nueva zelanda",
    "tamano_animal": "pequeno",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "calmada"
  },
{
    "nom_animal": "atun",
    "clase": "pez",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "liso",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "plateado",
    "reproduccion": "ovipara",
    "actitud": "calmado"
  },
{
    "nom_animal": "murcielago",
    "clase": "desmodontinos",
    "dieta": "frutiboro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "cuevas",
    "tamano_animal": "mediano",
    "color_caracteristico": "negro",
    "reproduccion": "viviparo",
    "actitud": "calmado"
  },
{
    "nom_animal": "campañol",
    "clase": "roedor",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "calmado"
  },
{
    "nom_animal": "buitre",
    "clase": "ave",
    "dieta": "carronero",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "variado",
    "tamano_animal": "mediano",
    "color_caracteristico": "negro",
    "reproduccion": "ovipara",
    "actitud": "calmada"
  },
{
    "nom_animal": "ualabi",
    "clase": "marsupial",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "sabana",
    "tamano_animal": "mediano",
    "color_caracteristico": "marron",
    "reproduccion": "vivipara",
    "actitud": "calmado"
  },
{
    "nom_animal": "avispa",
    "clase": "insecto",
    "dieta": "omnivoro",
    "extremidades": 6,
    "Tipo_de_pelaje": "bello",
    "sensacion_de_pelaje": "suave",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "amarillo",
    "reproduccion": "ovipara",
    "actitud": "agresivo"
  },
{
    "nom_animal": "lobo",
    "clase": "lupus",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "vivipara",
    "actitud": "agresiva"
  },
{
    "nom_animal": "gusano",
    "clase": "insecto",
    "dieta": "omnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "piel",
    "sensacion_de_pelaje": "aspera",
    "hogar": "multiple",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "ovipara",
    "actitud": "salvaje"
  },
{
    "nom_animal": "reyezuelo",
    "clase": "ave",
    "dieta": "insectivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "europa",
    "tamano_animal": "pequeno",
    "color_caracteristico": "verde",
    "reproduccion": "ovipara",
    "actitud": "tranquilo"
  },
{
    "nom_animal": "cerdo_hormiguero",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "antílope",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "sabana",
    "tamano_animal": "grande",
    "color_caracteristico": "cafe",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "Lobina negra",
    "clase": "peces",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "rio",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "oso",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "denso",
    "hogar": "bosque",
    "tamano_animal": "grande",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },

  {
    "nom_animal": "jabali",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "sabana",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },

  {
    "nom_animal": "bufalo",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "sabana",
    "tamano_animal": "grande",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },

  {
    "nom_animal": "becerra",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "granja",
    "tamano_animal": "mediano",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "carpa",
    "clase": "peces",
    "dieta": "herbivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "denso",
    "hogar": "granja",
    "tamano_animal": "muy pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "bagre",
    "clase": "peces",
    "dieta": "herbivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "granja",
    "tamano_animal": "pequeno",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "conejillo_de_Indias",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "pradera",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "guepardo",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "sabana",
    "tamano_animal": "grande",
    "color_caracteristico": "amarillo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "pollo",
    "clase": "aves",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "granja",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "chub",
    "clase": "peces",
    "dieta": "herbivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "almeja",
    "clase": "crustaceo",
    "dieta": "herbivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "blanco",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "cangrejo",
    "clase": "crustaceo",
    "dieta": "carnivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "amarillo",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "cerdo_hormiguero",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "cuervo",
    "clase": "aves",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "negro",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "ciervo",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "grande",
    "color_caracteristico": "amarillo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "cazon",
    "clase": "peces",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "grande",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "delfin",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "suave",
    "hogar": "rio",
    "tamano_animal": "grande",
    "color_caracteristico": "azul",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "paloma",
    "clase": "aves",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "pato",
    "clase": "aves",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "pluma",
    "sensacion_de_pelaje": "suave",
    "hogar": "granja",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "elefante",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "aspero",
    "hogar": "sabana",
    "tamano_animal": "enorme",
    "color_caracteristico": "gris",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "flamenco",
    "clase": "aves",
    "dieta": "omnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "rio",
    "tamano_animal": "mediano",
    "color_caracteristico": "rosa",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "pulga",
    "clase": "insectos",
    "dieta": "carnivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "sin_cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "cafe",
    "reproduccion": "oviparo",
    "actitud": "domestica"
  },
  {
    "nom_animal": "rana",
    "clase": "anfibio",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "lisa",
    "hogar": "rio",
    "tamano_animal": "pequeno",
    "color_caracteristico": "verde",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "murciélago_de_la_fruta",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "liso",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "negro",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "jirafa",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "sabana",
    "tamano_animal": "enorme",
    "color_caracteristico": "amarillo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "mosquito",
    "clase": "insectos",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "liso",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "cafe",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "cabra",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "granja",
    "tamano_animal": "mediano",
    "color_caracteristico": "ocre",
    "reproduccion": "viviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "gorilla",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "enorme",
    "color_caracteristico": "negro",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "gaviota",
    "clase": "aves",
    "dieta": "carnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "pequeno",
    "color_caracteristico": "blanco",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "eglefino",
    "clase": "peces",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "liso",
    "hogar": "mar",
    "tamano_animal": "mediano",
    "color_caracteristico": "multicolor",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "hamster",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "viviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "liebre",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "pequeno",
    "color_caracteristico": "pardo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "halcón",
    "clase": "aves",
    "dieta": "carnivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "pradera",
    "tamano_animal": "mediano",
    "color_caracteristico": "gris",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "arenque",
    "clase": "peces",
    "dieta": "carnivoro",
    "extremidades": 0,
    "Tipo_de_pelaje": "escamas",
    "sensacion_de_pelaje": "aspero",
    "hogar": "rio",
    "tamano_animal": "pequeno",
    "color_caracteristico": "azul",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "abeja",
    "clase": "insectos",
    "dieta": "herbivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "amarillo",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "mosca_doméstica",
    "clase": "insectos",
    "dieta": "omnivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "suave",
    "hogar": "ciudad",
    "tamano_animal": "pequeno",
    "color_caracteristico": "negro",
    "reproduccion": "oviparo",
    "actitud": "domestico"
  },
  {
    "nom_animal": "kiwi",
    "clase": "aves",
    "dieta": "herbivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "denso",
    "hogar": "bosque",
    "tamano_animal": "muy_pequeno",
    "color_caracteristico": "marron",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "mariquita",
    "clase": "insectos",
    "dieta": "herbivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "suave",
    "hogar": "bosque",
    "tamano_animal": "muy_pequeno",
    "color_caracteristico": "multicolor",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "alondra",
    "clase": "aves",
    "dieta": "herbivoro",
    "extremidades": 2,
    "Tipo_de_pelaje": "plumas",
    "sensacion_de_pelaje": "suave",
    "hogar": "ciudad",
    "tamano_animal": "muy_pequeno",
    "color_caracteristico": "amarillo",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "leopardo",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "aspero",
    "hogar": "montaña",
    "tamano_animal": "grande",
    "color_caracteristico": "amarillo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "leon",
    "clase": "mamifero",
    "dieta": "carnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "espeso",
    "hogar": "sabana",
    "tamano_animal": "grande",
    "color_caracteristico": "amarillo_quemado",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "langosta",
    "clase": "crustaceo",
    "dieta": "carnivoro",
    "extremidades": 8,
    "Tipo_de_pelaje": "sin_pelaje",
    "sensacion_de_pelaje": "aspero",
    "hogar": "mar",
    "tamano_animal": "mediano",
    "color_caracteristico": "rojo",
    "reproduccion": "oviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "lince",
    "clase": "mamifero",
    "dieta": "omnivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "espeso",
    "hogar": "bosque",
    "tamano_animal": "mediano",
    "color_caracteristico": "pardo",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  },
  {
    "nom_animal": "vison",
    "clase": "mamifero",
    "dieta": "herbivoro",
    "extremidades": 4,
    "Tipo_de_pelaje": "cabello",
    "sensacion_de_pelaje": "suave",
    "hogar": "rio",
    "tamano_animal": "pequeno",
    "color_caracteristico": "castano",
    "reproduccion": "viviparo",
    "actitud": "salvaje"
  }

]

"""El primer arbol no tiene una buena prediccion del animal por eso decidimos crear un segundo arbol ajustando las formulas y separando als funciones."""

#ARBOL 1
import random
#esta funcion nos permite visualizar el arbol
def print_tree(tree, indent=""):
    if isinstance(tree, tuple):
        feature, value, left, right = tree
        print(f"{indent}{feature} = {value}")
        print_tree(left, indent + "  ")
        print_tree(right, indent + "  ")
    else:
        print(f"{indent}Clase: {tree}")

def shuffle_data(data):
    random.shuffle(data)
#aqui calculamos la impureza de gini con respecto a todas mis clasificaciones
def calculate_gini(data):
    total_samples = len(data)
    if total_samples == 0:
        return 0

    gini = 1
    class_counts = {}
    for row in data:
        label = row["nom_animal"]
        class_counts[label] = class_counts.get(label, 0) + 1

    for label in class_counts:
        probability = class_counts[label] / total_samples
        gini -= probability ** 2

    return gini
#aqui dividimos lo sa datos
def split_data(data, feature, value):
    left = [row for row in data if row[feature] == value]
    right = [row for row in data if row[feature] != value]
    return left, right
#aqui me toma la mejor division para hacer el arbol y predecir la proxima opcion
def find_best_split(data, features):
    best_gini = 1
    best_feature = None
    best_value = None

    for feature in features:
        values = set(row[feature] for row in data)
        for value in values:
            left, right = split_data(data, feature, value)
            gini = (len(left) / len(data)) * calculate_gini(left) + (len(right) / len(data)) * calculate_gini(right)
            if gini < best_gini:
                best_gini = gini
                best_feature = feature
                best_value = value

    print("Mejor Split:")
    print("Característica:", best_feature)
    print("Valor:", best_value)
    print("Gini:", best_gini)

    return best_feature, best_value
#aqui construye el arbol
def build_tree(data, features):
    if not data:
        return None
    if len(set(row["nom_animal"] for row in data)) == 1:
        return data[0]["nom_animal"]
    if not features:
        return max(set(row["nom_animal"] for row in data), key=lambda x: [row["nom_animal"] for row in data].count(x))

    best_feature, best_value = find_best_split(data, features)
    left_data, right_data = split_data(data, best_feature, best_value)
    remaining_features = [f for f in features if f != best_feature]

    left_subtree = build_tree(left_data, remaining_features)
    right_subtree = build_tree(right_data, remaining_features)

    return (best_feature, best_value, left_subtree, right_subtree)
#en estas dos funciones nos predice el animal insertado
def predict(tree, samples):
    predictions = [_predict(tree, sample) for sample in samples]
    return predictions

def _predict(tree, sample):
    if not isinstance(tree, tuple):
        return tree
    feature, value, left, right = tree
    return _predict(left, sample) if sample[feature] == value else _predict(right, sample)

shuffle_data(animales)
#set de entrenamiento



total_datos = len(animales)
por_train = 0.7
tam_data_train = int(total_datos * por_train)

data_test = animales[tam_data_train:]

tree = build_tree(animales, ["clase", "dieta", "extremidades", "Tipo_de_pelaje", "sensacion_de_pelaje", "hogar", "tamano_animal", "color_caracteristico","reproduccion","actitud"])



import random

# set de entrenamiento
shuffle_data(animales)


por_train = 0.7
total_datos = len(animales)
tam_data_train = int(total_datos * por_train)

# guardamos los dos set en entrenamiento y prueba
data_train = animales
data_test = animales[tam_data_train:]

#hacemos la prediccion del animal
input = data_test

predictions = predict(tree, input)
print("-----------------------------------------------------------")
print("Tu animal pensado es:", predictions)

def calculate_accuracy(predictions, actual_labels):
    correct = sum(1 for prediction, actual in zip(predictions, actual_labels) if prediction == actual)
    accuracy = (correct / len(actual_labels)) * 100
    return accuracy
print("-----------------------------------------------------------")
print("Árbol de decisión:")
print_tree(tree)


actual_labels = [sample["nom_animal"] for sample in data_test]

accuracy = calculate_accuracy(predictions, actual_labels)

#ARBOL 2

#funcion para predecir animales
def predecir_animales(animales, arbol):
    predicciones = []
    for i, animal in enumerate(animales):
        resultado = predecir_animal(animal, arbol)
        print(f"la predicción es {resultado}")

#funcion para imprimir el arbol
def print_tree(tree, indent=""):
    if isinstance(tree, tuple):
        feature, value, left, right = tree
        print(f"{indent}{feature} = {value}")
        print_tree(left, indent + "  ")
        print_tree(right, indent + "  ")
    else:
        print(f"{indent}Clase: {tree}")

#cual es la clase mas comun

def clase_mas_comun(data):
    clas = [fila["nom_animal"] for fila in data]
    return max(set(clas), key=clas.count)

def calcular_gini(data):
    if not data:
        return 0.0

    clas = [fila["nom_animal"] for fila in data]
    tot = len(clas)
    impu = 1.0

    for clase in set(clas):
        prob = clas.count(clase) / tot
        impu -= prob ** 2
    return impu

def find_best_split(data, features):
    best_gini = 1
    best_feature = None
    best_value = None

    for feature in features:
        values = set(row[feature] for row in data)
        for value in values:
            left, right = split_data(data, feature, value)
            gini = (len(left) / len(data)) * calculate_gini(left) + (len(right) / len(data)) * calculate_gini(right)
            if gini < best_gini:
                best_gini = gini
                best_feature = feature
                best_value = value

    print("Mejor Split:")
    print("Característica:", best_feature)
    print("Valor:", best_value)
    print("Gini:", best_gini)

    return best_feature, best_value

def predecir_animal(animal, arbol):
    if isinstance(arbol, dict):
        atributo = arbol["atributo"]
        valor = arbol["valor"]
        if animal.get(atributo) == valor:
            return predecir_animal(animal, arbol["izquierdo"])
        else:
            return predecir_animal(animal, arbol["derecho"])
    else:
        return arbol

def construir_arbol(data):
    if not data:
        return clase_mas_comun(data)

    clases = set(fila["nom_animal"] for fila in data)


    if len(clases) == 1:
        return clases.pop()


    if len(data[0]) == 1:
        return clase_mas_comun(data)


    mejor_gini = 1.0
    mejor_division = None

    for atributo in data[0]:
        if atributo != "nom_animal":
            valores = set(fila[atributo] for fila in data)
            for valor in valores:
                conjunto_izquierda = [fila for fila in data if fila[atributo] == valor]
                conjunto_derecha = [fila for fila in data if fila[atributo] != valor]

                gini_izquierda = calcular_gini(conjunto_izquierda)
                gini_derecha = calcular_gini(conjunto_derecha)

                gini_total = (len(conjunto_izquierda) / len(data)) * gini_izquierda + (len(conjunto_derecha) / len(data)) * gini_derecha

                if gini_total < mejor_gini:
                    mejor_gini = gini_total
                    mejor_division = (atributo, valor, conjunto_izquierda, conjunto_derecha)

    if mejor_gini == 1.0:
        return clase_mas_comun(data)
    atributo, valor, conjunto_izquierda, conjunto_derecha = mejor_division
    subarbol_izquierdo = construir_arbol(conjunto_izquierda)
    subarbol_derecho = construir_arbol(conjunto_derecha)

    return {"atributo": atributo, "valor": valor, "izquierdo": subarbol_izquierdo, "derecho": subarbol_derecho}

arbol_decision = construir_arbol(data_train)

print("-----------------------------------------------------------")
print("Árbol de decisión:")
print_tree(tree)

nuevos_animales = data_test
predicciones = predecir_animales(nuevos_animales, arbol_decision)